version: "3.8"

services:
  app:
    build: .
    container_name: mugi-interview-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "default"
      JAVA_TOOL_OPTIONS: "-Xms512m -Xmx1024m"
    volumes:
      - logs:/app/logs
    depends_on:
      - db
    networks:
      - spring-boot-network

  db:
    image: h2database/h2
    container_name: h2-database
    ports:
      - "1521:1521"
      - "8082:8082" # Web console
    environment:
      H2_OPTIONS: "-tcp -tcpAllowOthers -webAllowOthers"
    networks:
      - spring-boot-network

networks:
  spring-boot-network:

volumes:
  logs: